apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: governos-api

configMapGenerator:
  - name: governos-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
