name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest

    - name: Install dependencies
      run: poetry install

    - name: Run Ruff Check
      run: poetry run ruff check .

    - name: Run MyPy
      run: poetry run mypy .

    - name: Run Pytest
      run: poetry run pytest --cov=intentgraph tests/
